import React, { Component } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import Image from 'next/image'

// import rootReducer from '../redux/reducers/_root.reducer'
// import rootSaga from '../redux/sagas/_root.saga'
// import { Provider } from 'react-redux'

import Navigation from "./components/navigation.js"



class Home extends Component {

  state = {
    yuki: {
      name: "Yuki Carlisle",
      species: "felis catus",
    },
    cookies: 0,
    color: "white",
  }

  rainbow = ["red", "orange", "yellow", "green", "blue", "indigo", "violet"]

  handleInputChangeFor = (propertyName) => (event) => {
    this.setState({
      [propertyName]: event.target.value,
    })
  }

  addOneCookie = () => {
    this.setState(prevState => {
      return { cookies: prevState.cookies + 1, color: Math.random(this.rainbow) }
    })
    console.log("You got a cookie.")
    // How to change the state color to a random color from the rainbow array.
  }

  changeCounterColor = () => {
    this.setState(prevState => {
      return {color: "blue"}
    })
  }


  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation />

        <main className={styles.main}>

          <h1>Saviland Net</h1>


          <div id="cookie-clicker"
            style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
            <button onClick={this.addOneCookie}>🍪</button>
            <p style={{ color: this.state.color }}>{this.state.cookies}</p>
          </div>








        </main>

        <footer className={styles.footer}>

        </footer>

      </div>
    )
  }
}

const mapStoreToProps = (reduxState) => ({
  data: reduxState.data
})

export default Home
