import React, { Component } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import Image from 'next/image'

// import rootReducer from '../redux/reducers/_root.reducer'
// import rootSaga from '../redux/sagas/_root.saga'
// import { Provider } from 'react-redux'

import Navigation from "./components/navigation.js"
import Message from "./components/message.js"


class Home extends Component {

  state = {
    yuki: true,
    meows: 0
  }

  handleInputChangeFor = (propertyName) => (event) => {
    this.setState({
      [propertyName]: event.target.value,
    })
  }

  meow = () => {
    this.setState(prevState => {
      return { meows: prevState.meows + 1 }
    })
    console.log("meow")
  }


  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation />

        <main className={styles.main}>

          <h1>Saviland Net</h1>

          <button onClick={this.meow} >Meow</button>
          <p>Meows: {this.state.meows}</p>


          <Message />

        </main>

        <footer className={styles.footer}>

        </footer>

      </div>
    )
  }
}

export default Home



// Dustins command handler
// handleInputChangeFor = (propertyName) => (event) => {
//   this.setState({
//     [propertyName]: event.target.value,
//   })
// }



// export default function Home() {





//   return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <Navigation />

    //   <main className={styles.main}>

    //     <h1>Saviland Net</h1>
    //     <h2>What is Saviland?</h2>
    //     <p>Saviland Net will host applications online.</p>
    //     <div>Such applications include, but are not limited to: <br />
    //       Chatspace, Saviland Net
    //     </div>

    //     <Message />

    //   </main>

    //   <footer className={styles.footer}>

    //   </footer>

    // </div>
//   )
// }
