import React, { Component } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Navigation from "./components/navigation.js"
import WelcomeMessage from './components/welcomeMessage'

class Home extends Component {

  state = {
    yuki: {
      name: "Yuki Carlisle",
      species: "felis catus",
    },
    cookies: 0,
    color: "white",
  }

  rainbow = ["red", "orange", "yellow", "green", "blue", "indigo", "violet"]

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation />

        <main className={styles.main}>

          <h1>Saviland Net</h1>

          <WelcomeMessage />

        </main>

        <footer className={styles.footer}>

        </footer>

      </div>
    )
  }
}

const mapStoreToProps = (reduxState) => ({
  data: reduxState.data
})

export default Home
